export const OVERVIEW_READ = 'OVERVIEW_READ'; // 总览
export const DIAGRAM_READ = 'DIAGRAM_READ'; // 运行概览
export const DC_READ = 'DC_READ'; // 直流系统
export const ENVIRONMENTAL_READ = 'ENVIRONMENTAL_READ'; // 环境监测
export const ALARM_READ = 'ALARM_READ'; // 异常报警
export const ALARM_WRITE = 'ALARM_WRITE';
export const MANUAL_ALARM_READ = 'MANUAL_ALARM_READ'; // 安全隐患
export const MANUAL_ALARM_WRITE = 'MANUAL_ALARM_WRITE';
export const REPORT_READ = 'REPORT_READ'; // 管理报告
export const REPORT_WRITE = 'REPORT_WRITE';
export const ASSET_READ = 'ASSET_READ'; // 资产档案
export const ASSET_WRITE = 'ASSET_WRITE';
export const ENERGY_EFFICIENCY_READ = 'ENERGY_EFFICIENCY_READ'; // 能效概览
export const STATISTICAL_REPORT_READ = 'STATISTICAL_REPORT_READ'; // 统计报表
export const EP_ANALYSIS_READ = 'EP_ANALYSIS_READ'; // 电量统计
export const LOSS_READ = 'LOSS_READ'; // 损耗分析
export const POWER_ANALYSIS_READ = 'POWER_ANALYSIS_READ'; // 电量统计 用电构成 分时电量 敷在分析 电费分析 报装方式 功率因素
export const HISTORY_READ = 'HISTORY_READ'; // 电量 功率 电流 相电压 线电压 功率因素 温度
export const PROJECT_READ = 'PROJECT_READ'; // 项目管理
export const PROJECT_WRITE = 'PROJECT_WRITE';
export const LOSS_WRITE = 'LOSS_WITE';
export const REPORTED_INSTALLATION_READ = 'REPORTED_INSTALLATION_READ'; //电费报装
export const REPORTED_INSTALLATION_WRITE = 'REPORTED_INSTALLATION_WRITE';
export const PERMISSION_READ = 'PERMISSION_READ'; // 权限管理
export const PERMISSION_WRITE = 'PERMISSION_WRITE';
export const USER_READ = 'USER_READ'; // 人员管理
export const USER_WRITE = 'USER_WRITE';
export const INSPECTION_PLAN_READ = 'INSPECTION_PLAN_READ'; // 巡检计划
export const INSPECTION_PLAN_WRITE = 'INSPECTION_PLAN_WRITE';
export const TICKET_STAT_READ = 'TICKET_STAT_READ'; // 工单统计
export const ROTA_READ = 'ROTA_READ'; // 值班管理
export const ROTA_WRITE = 'ROTA_WRITE';
export const TICKET_READ = 'TICKET_READ'; // 工单
export const TICKET_WRITE = 'TICKET_WRITE';
export const TICKET_ADMIN = 'TICKET_ADMIN'; // 工单分配
